SET C51INC=E:\Program Files\Keil_v5\C51\Inc;E:\Program Files\Keil_v5\C51\Inc\Atmel
SET C51LIB=E:\Program Files\Keil_v5\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"E:\Program Files\Keil_v5\C51\BIN\A51.EXE" @STARTUP._ia
"E:\Program Files\Keil_v5\C51\BIN\C51.EXE" @¿Î³Ì³ÌÐò.__i
"E:\Program Files\Keil_v5\C51\BIN\BL51.EXE" @programs.lnp
"E:\Program Files\Keil_v5\C51\BIN\OH51.EXE" "programs" 
